import { Link } from "react-router-dom";
import type { ReactNode } from "react";

/**
 * The disclaimer is a fixed part of the page frame rather than something a screen opts
 * into, so there is no route that can render a prediction without it.
 */
export function Disclaimer({ text }: { text?: string }) {
  return (
    <p className="text-xs leading-relaxed text-muted">
      {text ??
        "For research and educational purposes only. Predictions generated by this system are based on machine-learning models trained on historical public datasets and must not be interpreted as medical diagnosis or professional medical advice."}
    </p>
  );
}

export function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="min-h-screen">
      <header className="border-b border-line bg-surface">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4">
          <Link to="/" className="flex items-baseline gap-2">
            <span className="text-base font-semibold tracking-tight">Multi-Disease AI</span>
            <span className="text-xs text-muted">Explainable risk prediction</span>
          </Link>
          <span className="chip bg-canvas text-muted">Research &amp; education only</span>
        </div>
      </header>
      <main className="mx-auto max-w-5xl px-5 py-8">{children}</main>
      <footer className="mx-auto max-w-5xl px-5 pb-12 pt-4">
        <div className="border-t border-line pt-4">
          <Disclaimer />
          <p className="mt-2 text-xs text-muted">
            Three independent models over three unrelated public datasets. They are never
            combined, and this platform produces no overall health score.
          </p>
        </div>
      </footer>
    </div>
  );
}

export function Banner({
  tone = "info",
  title,
  children,
}: {
  tone?: "info" | "warn" | "flag";
  title?: string;
  children: ReactNode;
}) {
  const tones = {
    info: "border-line bg-canvas text-ink",
    warn: "border-warn/25 bg-warnBg text-ink",
    flag: "border-flagged/25 bg-flaggedBg text-ink",
  };
  return (
    <div className={`rounded-md border px-4 py-3 text-sm ${tones[tone]}`}>
      {title && <p className="mb-1 font-semibold">{title}</p>}
      <div className="leading-relaxed">{children}</div>
    </div>
  );
}

export function Spinner({ label }: { label: string }) {
  return (
    <div className="flex items-center gap-3 py-16 text-sm text-muted">
      <span className="h-4 w-4 animate-spin rounded-full border-2 border-line border-t-accent" />
      {label}
    </div>
  );
}

export function ErrorBox({ error, onRetry }: { error: string; onRetry?: () => void }) {
  return (
    <Banner tone="warn" title="Something went wrong">
      <p>{error}</p>
      <p className="mt-2 text-xs">
        If the API is not running, start it with{" "}
        <code className="rounded bg-surface px-1 py-0.5">uvicorn backend.main:app</code> from
        the project root.
      </p>
      {onRetry && (
        <button className="btn-secondary mt-3" onClick={onRetry}>
          Try again
        </button>
      )}
    </Banner>
  );
}
