"""saved analyses

Revision ID: 22d2fddcb8e7
Revises: 61b46b0d8128
Create Date: 2026-09-04 11:14:23.684880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d2fddcb8e7'
down_revision: Union[str, Sequence[str], None] = '61b46b0d8128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('disease', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('band_label', sa.String(length=16), nullable=False),
    sa.Column('band_lower', sa.Float(), nullable=False),
    sa.Column('band_upper', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('calibration', sa.String(length=32), nullable=False),
    sa.Column('imputed_features', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analyses_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index('ix_analyses_user_created')

    op.drop_table('analyses')
    # ### end Alembic commands ###
