"""Run EDA for one or all diseases: profile JSON + figures + EDA.md summary.

Usage:
    python -m ml.eda.run              # heart, kidney, diabetes
    python -m ml.eda.run heart        # a single disease
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

from config import DISEASES, REPORTS_DIR
from ml.data.loaders import LOADERS
from ml.eda import plots, profile
from ml.eda.profile import (
    categorical_summary,
    class_imbalance_ratio,
    correlation_matrix,
    missing_value_table,
    numeric_summary,
    target_distribution,
    target_feature_association,
)


def _json_default(o):
    if isinstance(o, (pd.Timestamp,)):
        return str(o)
    raise TypeError(type(o))


def run_eda(disease: str) -> dict:
    if disease not in LOADERS:
        raise KeyError(disease)
    X, y, spec = LOADERS[disease]()
    out_dir = REPORTS_DIR / disease
    fig_dir = out_dir / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)

    prof = profile.full_profile(X, y, spec)
    (out_dir / "eda_profile.json").write_text(json.dumps(prof, indent=2, default=_json_default), encoding="utf-8")

    # CSV artefacts (handy for the analytics API and for spreadsheets).
    missing_value_table(X).to_csv(out_dir / "missing_values.csv", index=False)
    numeric_summary(X, spec).to_csv(out_dir / "numeric_summary.csv")
    corr = correlation_matrix(X, spec)
    if not corr.empty:
        corr.to_csv(out_dir / "correlation_matrix.csv")

    figs = plots.all_eda_plots(X, y, spec, fig_dir)

    _write_eda_md(disease, X, y, spec, prof, figs, out_dir)
    return prof


def _write_eda_md(disease, X, y, spec, prof, figs, out_dir: Path) -> None:
    ov = prof["overview"]
    td = target_distribution(y)
    mvt = missing_value_table(X)
    mvt_nonzero = mvt[mvt["n_missing"] > 0]
    assoc = target_feature_association(X, y, spec).head(10)

    lines = [
        f"# Exploratory Data Analysis — {DISEASES[disease]['label']}",
        "",
        f"- Rows: **{ov['n_rows']}**  |  Features: **{ov['n_features']}** "
        f"({ov['n_numeric']} numeric, {ov['n_categorical']} categorical, {ov['n_binary']} binary)",
        f"- Duplicate rows: {ov['duplicate_rows']}",
        f"- Rows with any missing value: {ov['rows_with_any_missing']} "
        f"({100 * ov['rows_with_any_missing'] / ov['n_rows']:.1f}%)",
        f"- Total missing cells: {ov['total_missing_cells']}",
        "",
        "## Target distribution",
        "",
        "| class | count | proportion |",
        "|---|---|---|",
    ]
    for _, r in td.iterrows():
        lines.append(f"| {int(r['class'])} | {int(r['count'])} | {r['proportion']:.4f} |")
    lines += [
        "",
        f"Class-imbalance ratio (majority / minority): **{class_imbalance_ratio(y)}**",
        "",
        "## Missing values",
        "",
    ]
    if mvt_nonzero.empty:
        lines.append("No missing values in any predictor column.")
    else:
        lines += ["| column | dtype | n_missing | pct_missing |", "|---|---|---|---|"]
        for _, r in mvt_nonzero.iterrows():
            lines.append(f"| `{r['column']}` | {r['dtype']} | {r['n_missing']} | {r['pct_missing']}% |")
    lines += [
        "",
        "## Top |correlation| of numeric features with the target (descriptive only)",
        "",
        "| feature | corr with target |",
        "|---|---|",
    ]
    for _, r in assoc.iterrows():
        lines.append(f"| `{r['feature']}` | {r['corr_with_target']:+.3f} |")

    lines += ["", "## Figures", ""]
    for f in figs:
        rel = f.relative_to(out_dir).as_posix()
        lines.append(f"![{f.stem}]({rel})")
        lines.append("")

    lines += [
        "## Outlier scan (IQR fences — diagnostic only, nothing removed)",
        "",
        "See `eda_profile.json -> outlier_scan`. Medical measurements legitimately contain "
        "extreme values; outliers are flagged, not dropped.",
        "",
        "---",
        "*Generated by `python -m ml.eda.run`. Re-run after any loader change.*",
    ]
    (out_dir / "EDA.md").write_text("\n".join(lines), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    targets = argv if argv else list(DISEASES)
    for disease in targets:
        print(f"\n=== EDA: {disease} ===")
        prof = run_eda(disease)
        ov = prof["overview"]
        print(f"  {ov['n_rows']} rows x {ov['n_features']} features; "
              f"missing cells={ov['total_missing_cells']}; imbalance={prof['class_imbalance_ratio']}")
        print(f"  wrote {REPORTS_DIR / disease}/ (eda_profile.json, EDA.md, figures/, *.csv)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
